services:
  db:
    image: lanterndata/lantern-suite:pg15-v0.1.18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SecurePassword123!
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
      - 6432:6432
    volumes:
      - db_cache:/var/lib/postgresql/data

volumes:
  db_cache:
    driver: local
